### PR TITLE
feat: accessibility!

### PR DESCRIPTION
**Pull request by varjmes**
Hey Hey!

Noticed a couple things that could use some improvement, so I thought I'd take a shot.
1. The `$grey` colour you were using didn't have the best contrast levels, meaning it could be hard to see by folk with poor vision. So, I updated the colour!

Before:

kap-before

After:

kap-after
1. I had to work out how to make the changes in this repo myself, so I documented how to do this in the README.

Hope this helps 🌞 
Great app, I hope it gets bigger and better :)

### CODE REVIEW

**Comment by doot0** [comment]
Thanks so much! Code LGTM 👍 
cc @skllcrn Design review?

**Comment by matheuss** [comment]
Amazing @Charlotteis 😍

**Comment by timothyis** [comment]
Wow! Thanks for this @Charlotteis. Accessibility is super important to me!
Thanks for the README update too! 

Could you tell me the name of the plugin you used for the colour tests?

**Comment by skllcrn** [comment]
Thank you @Charlotteis! Let's get this fix live 🙌

**Comment by varjmes** [comment]
Wow y'all are so nice and speedy in your responses 👍 

@CodeTheory I use http://khan.github.io/tota11y/!

**Comment by timothyis** [comment]
Brilliant, thank you!

**Pull request merged**
